config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get 'welcome/index'
  get 'welcome/terms'
  get 'welcome/privacy'
  get 'welcome/ifconfig'
  get 'index', {controller: :welcome_controller, action: :index}

  get 'patient_server', {controller: :patient_server, action: :show}
  post 'patient_servers', {controller: :patient_server, action: :create}

  get 'identity_matchings/example'
  resources :identity_matchings, except: [:edit, :update]

  get 'oauth2/start'
  get 'oauth2/restart'
  get 'oauth2/redirect'
  #post 'oauth2/register'

  get 'udap/start'
  get 'udap/register'
  get 'udap/redirect'

  resources :authorities

end

app/models/identity_matching.rb
class IdentityMatching < ApplicationRecord
  # This model handles a IDIPatient profile, converting to/from FHIR JSON,
  # sending request, and receiving response. Relies on active record validations
  # to make this client's IDIPatient profile conform to IG, although technically
  # only the server needs do validation.
  #
  # See: http://build.fhir.org/ig/HL7/fhir-identity-matching-ig/artifacts.html

  # IDI Patient Level
  enum :idi_level, [ :idi_patient_base, :idi_patient_l0, :idi_patient_l1 ]

  # Photo
  has_one_attached :photo

  # Validations
  #validates :full_name, presence: true # only for IDI L1
  #validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
  #validates :mobile, format: { with: /A(\+\d{1,2}\s)?\(?\d{3}\)?[\s.-]?\d{3}[\s.-]?\d{4}\z/ }
  validates_with WeightValidator

  # Load fhir profiles as JSON ERB templates
  MATCH_PARAMETER_ERB = ERB.new(File.read(Rails.root.join('resources', 'match_parameter.json.erb')))
  IDI_BASE_PARAMETER = ERB.new(File.read(Rails.root.join('resources', 'idi_base_parameter.json.erb')))
  IDI_L0_PARAMETER = ERB.new(File.read(Rails.root.join('resources', 'idi_level0_parameter.json.erb')))
  IDI_L1_PARAMETER = ERB.new(File.read(Rails.root.join('resources', 'idi_level1_parameter.json.erb')))

  # Identifier code system from IDIPatient Profile
  IDENTIFIER_SYSTEM = "http://terminology.hl7.org/CodeSystem/v2-0203";

  # parse request body as FHIR
  # returns: FHIR::Model instance OR nil
  def request_fhir
	return nil unless self.request_json
	FHIR.from_contents(self.request_json)
  end

  # parses fhir model into request body json
  # param fhir_obj: FHIR::Model instance
  # returns: nil or string (json)
  def request_fhir=(fhir_obj)
	return nil unless fhir_obj.is_a? FHIR::Model
	self.request_json = fhir_obj.to_json
  end

  # parse response body as FHIR
  # returns: FHIR::Model instance OR nil
  def response_fhir
	return nil unless self.response_json
	FHIR.from_contents(self.response_json)
  end

  # parses fhir model into response body json
  # param fhir_obj: FHIR::Model instance
  # returns nil or string (json)
  def response_fhir=(fhir_obj)
	return nil unless fhir_obj.is_a? FHIR::Model
	self.response_json = fhir_obj.to_json	
  end

  # parse full name and return last name
  # returns: string
  def last_name
	return "" unless self.full_name.strip.include? ' '
	self.full_name.strip.titleize.split.last
  end

  # parse full name and return all other names
  # returns: array of strings
  def given_names
	names = self.full_name.strip.titleize.split
	names.pop
	names
  end

  # returns: boolean (true if given_names is not empty array, otherwise false)
  def given_names?
	!!self.given_names&.empty?
  end

  # return pretty string for address
  def address
	return "#{address_line1} #{address_line2}\n#{city} #{state} #{zipcode}"
  end

  # return true if any hard identifier is provided
  def identifiers?
    return [:drivers_license, :national_insurance_payor_identifier, :state_id_number, :passport_number].any? { |x| self.has? x }
  end

  # returns array of hashes that is convenient for templating fhir identifiers
  # reference: http://build.fhir.org/ig/HL7/fhir-identity-matching-ig/ValueSet-Identity-Identifier-vs.html
  def identifiers
	ret = []
	ret << {system: IDENTIFIER_SYSTEM, code: 'DL', display: 'Drivers License', value: self.drivers_license} if self.has? :drivers_license
	ret << {system: IDENTIFIER_SYSTEM, code: 'NIIP', display: 'National Insurance Payor Identifier', value: self.national_insurance_payor_identifier} if self.has? :national_insurance_payor_identifier
	ret << {system: IDENTIFIER_SYSTEM, code: 'STID', display: 'State Level Identifier', value: self.state_id_number} if self.has? :state_id_number
	ret << {system: IDENTIFIER_SYSTEM, code: 'PPN', display: 'Passport Number', value: self.passport_number} if self.has? :passport_number
	ret
  end

  # Constructs fhir json artifact from model attributes
  # Utilizes files in resources/
  # Uses fhir_models gem to validate
  # Will overwrite old request fhir construct
  # returns: true if fhir model is valid and saves successfully ELSE
  #          false
  def build_request_fhir
	if self.idi_patient_l0?
		fhir_json = IDI_L0_PARAMETER.result_with_hash({model: self})
	elsif self.idi_patient_l1?
		fhir_json = IDI_L1_PARAMETER.result_with_hash({model: self})
	else
		fhir_json = IDI_BASE_PARAMETER.result_with_hash({model: self})
        puts fhir_json
	end
    self.request_json = fhir_json
	#self.request_fhir = FHIR.from_contents(fhir_json)
	#self.request_fhir.valid? && self.save
  end

  # TODO: use l0 or l1 profiles

  # param sym: symbol (for attribute)
  # returns: true if model has attribute string and string is not empty
  def has?(sym)
	!!( self.send(sym) && self.send(sym).respond_to?(:'empty?') && !self.send(sym).empty? )
  end

  # Compute "input quality and security" weight from model attributes according to IG
  # returns: int (weight)
  def weight
	total = 0;
	if self.has? :passport_number
		# NOTE: Assumes US Passport number, although IG allows any nation's passport number,
        #       in which case condition would be self.has?(:passport_number) && self.has?(:country)
		total += 10;
	end
	if self.has?(:drivers_license) || self.has?(:state_id_number)
		total += 10;
	end
	if self.has?(:address_line1) && (self.has?(:zipcode) || (self.has?(:city) && self.has?(:state))) ||
	   self.has?(:email) ||
	   self.has?(:mobile) ||
	   self.has?(:national_insurance_payor_identifier) ||
	   self.photo.attached? then
		total += 4;
	end
	if self.full_name&.split.length > 1
		total += 4;
	end
	if self.date_of_birth
		total += 2;
	end
	total
  end


  # returns number of matches found by server response
  # will return 0 even if request was never made
  # returns: int
  def number_of_matches
	self.response_fhir.send(:total) || 0
  end

end

app/controllers/identity_matchings_controller.rb
class IdentityMatchingsController < ApplicationController
  before_action :set_patient_server
  before_action :set_identity_matching, only: %i[ show edit update destroy ]

  # GET /identity_matchings
  def index
    @identity_matchings = IdentityMatching.all
  end

  # GET /identity_matching/1
  def show
  end

  # GET /identity_matching/new
  def new
    @identity_matching = IdentityMatching.new
  end

  # GET /identity_matching/1/edit
  def edit
  end

  # POST /identity_matchings
  def create
    @identity_matching = IdentityMatching.new(identity_matching_params)

	# Save inputs
	if !@identity_matching.has?(:request_json) then # build fhir json from model attributes
		# Save model and run IDILevels validation
		if !@identity_matching.save
			flash.now.alert = "Save failed on client side, please check inputs."
			render :new, status: :unprocessable_entity and return
		end

		# Build IDI Patient Profile and validate
		if !@identity_matching.build_request_fhir
			flash.now.alert = "Save failed on client side, inputs do not conform to IDI Patient Profile."
			render :new, status: :unprocessable_entity and return
		end
	else # validate provided fhir request
		# check JSON
		begin
			JSON.parse(@identity_matching.request_json)
		rescue JSON::ParserError => exception
			flash.now.alert = "Operation failed on client side - invalid JSON: #{exception}"
			render :new, status: :unprocessable_entity and return
		rescue Exception => exception
			flash.now.alert = "Operation failed on client side - exception: #{exception}"
			render :new, status: :unprocessable_entity and return
		end

		# check FHIR
		if !@identity_matching.request_fhir.valid?
			flash.now.alert = "Operation rejected by client - invalid FHIR input: #{@identity_matching.request_fhir.validate}"
			render :new, status: :unprocessable_entity and return
		end
	end

	# Send $match request to server with FHIR payload
	payload = @identity_matching.request_fhir.to_json
	headers = {'Accept' => 'application/fhir+json', 'Content-Length' => payload.length.to_s, 'Content-Type' => 'application/fhir+json'}
	headers.merge!({'Authorization' => "Bearer #{ENV['BEARER_TOKEN']}"}) if ENV.key? 'BEARER_TOKEN'
	begin
		response = RestClient.post(@patient_server.endpoint, payload, headers);
		@identity_matching.response_status = response.code
		@identity_matching.response_json = response.body
		@identity_matching.save!
	rescue RestClient::ExceptionWithResponse => exception
		@identity_matching.response_status = exception.response.code
		@identity_matching.response_json = exception.to_json
		@identity_matching.save!
		redirect_to @identity_matching, alert: "FHIR Server rejected payload" and return
	rescue Exception => exception
		@identity_matching.response_status = nil
		@identity_matching.response_json = exception.to_json
		@identity_matching.save
		redirect_to @identity_matching, alert: "FHIR Operation could not reach server #{@patient_server.endpoint}." and return
	end

	# Validate response
	if !@identity_matching.response_fhir.valid?
		redirect_to @identity_matching, alert: "Server returned invalid FHIR response." and return
	end

	# Interpret response
	n = @identity_matching.number_of_matches
	if n > 0
		redirect_to @identity_matching, notice: "#{n} #{'match'.pluralize(n)} found!" and return
	else
		redirect_to @identity_matching, notice: "FHIR Matching preformed, no matches found." and return
	end
  end

  # PATCH/PUT /identity_matching/1 or /identity_matching/1.json
  def update

	if !@identity_matching.update(identity_matching_params)
	  render :edit, alert: "Update failed on client side, input does not validate..." and return
	end

	# TODO flesh out
	raise StandardError.new "Not Implemented"
  end

  # DELETE /identity_matching/1 or /identity_matching/1.json
  def destroy
    @identity_matching.destroy

    respond_to do |format|
      format.html { redirect_to new_identity_matching_url, notice: "Patient identity record deleted.", status: :see_other }
    end
  end

  # GET /identity_matching/example
  def example
	@payload = File.read(Rails.root.join('resources', 'example_match_parameter.json'));
	conn = Faraday.new(url: @patient_server.endpoint, headers: {'Content-Type' => 'application/fhir+json'}) do |faraday|
	  faraday.response :logger, nil, {bodies: true, log_level: :debug}
	  faraday.response :raise_error
	end
	begin
		@response = conn.post do |req| req.body = @payload end
		flash.now.notice = 'Identity matching success'
	rescue Exception => exception
		flash.now.alert = "Failed to query #{@paient_server.endpoint}"
		@response = exception.to_s
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_identity_matching
      @identity_matching = IdentityMatching.find(params[:id])
    end

    # Whitelist of input parameters
    def identity_matching_params
	  permitted_inputs = [
		:full_name,
		:gender,
		:date_of_birth,
		:address_line1,
		:address_line2,
		:city,
		:state,
		:zipcode,
		:email,
		:mobile,
		:language,
		:drivers_license,
		:national_insurance_payor_identifier,
		:passport_number,
		:state_id_number,
		:idi_level,
		:request_json,
	  ]

      params.require(:identity_matching).permit( *permitted_inputs )
    end

end

app/views/identity_matchings/_errors.html.erb
<%# param: identity_matching - IdentityMatchingRequest instance with errors %>

<div class="alert alert-danger">
  <h2><%= pluralize(identity_matching.errors.count, "error") %> occurred:</h2>

  <ul>
    <% identity_matching.errors.each do |error| %>
      <li><%= error.full_message %></li>
    <% end %>
  </ul>
</div>

app/views/identity_matchings/_form.html.erb
<%= form_with(model: identity_matching) do |form| %>
  <%= form.hidden_field :language, {value: 'en-US'} %>

  <% if identity_matching.errors.any? %>
	<%= render "errors", identity_matching: identity_matching %>
  <% end %>

  <div class="container">
	<div class="row mb-2">
	  <div class="col">
	    <%= form.text_field :full_name, class: "form-control", placeholder: "Full Name" %>
	  </div>

	  <div class="col">
	    <%= form.text_field :gender, class: "form-control", placeholder: "Gender" %>
	  </div>

	  <div class="col">
		<div class="container-fluid">
		  <div class="row">
			<div class="col-md-3 col-4 text-center align-middle">
			  <b class="align-middle">Date of Birth:</b>
			</div>
			<div class="col-md-9 col-8">
		      <%= form.date_field :date_of_birth, class: "form-control", aria_label: "date_of_birth", aria_describedby: "date_of_birth_label" %>
			</div>
		  </div>
		</div>
	  </div>
	</div>

	<hr />

	<div class="row mb-2">
	  <strong><%= form.label "Address", class: "form-label" %></strong>
	</div>

	<div class="row mb-2">
	  <div class="col">
	    <%= form.text_field :address_line1, class: "form-control", placeholder: "Address Line 1" %>
	  </div>

	  <div class="col">
	    <%= form.text_field :address_line2, class: "form-control", placeholder: "Address Line 2" %>
	  </div>
	</div>

	<div class="row mb-2">
	  <div class="col">
		<%= form.text_field :city, class: "form-control", placeholder: "City" %>
	  </div>

	  <div class="col">
	    <%= form.text_field :state, class: "form-control", placeholder: "State" %>
	  </div>

	  <div class="col">
	    <%= form.text_field :zipcode, class: "form-control", placeholder: "Zipcode" %>
	  </div>
    </div>

	<hr />

	<div class="row mb-2">
	  <div class="col">
		<%= form.email_field :email, class: "form-control", placeholder: "Email" %>
	  </div>

	  <div class="col">
	    <%= form.telephone_field :mobile, class: "form-control", placeholder: "Phone Number" %>
	  </div>
	</div>

    <hr />

	<div class="row mb-2">
	  <div class="col">
		<strong>Identifiers</strong>
	  </div>
	</div>

	<div class="row mb-2">
	  <div class="col-6">
		<%= form.text_field :drivers_license, class: "form-control", placeholder: "Driver's License" %>
	  </div>
	  <div class="col-6">
		<%= form.text_field :national_insurance_payor_identifier, class: "form-control", placeholder: "National Insurance Payer Identifier" %>
	  </div>
	</div>

	<div class="row mb-2">
	  <div class="col-6">
		<%= form.text_field :passport_number, class: "form-control", placeholder: "Passport Number" %>
	  </div>
	  <div class="col-6">
		<%= form.text_field :state_id_number, class: "form-control", placeholder: "State ID" %>
	  </div>
	</div>

	<hr />

	<div class="row mb-2 justify-content-around">
	  <div class="col-auto">
	    <%= form.button "IDI Base Match", type: "submit", name: "identity_matching[idi_level]", value: "idi_patient_base", class: "btn btn-primary",
						data: { 'bs-toggle' => 'tooltip', 'bs-html' => 'true', 'bs-title' => 'Submit <b>any amount</b> of valuable information' }
		%>
	  </div>
	  <div class="col-auto">
	    <%= form.button "IDI Level 0 Match", type: "submit", name: "identity_matching[idi_level]", value: "idi_patient_l0", class: "btn btn-warning",
						data: { 'bs-toggle' => 'tooltip', 'bs-html' => 'true', 'bs-title' => 'Submit valuable information with a promised minimum <b>weighted value score of 10</b>' }
		%>
	  </div>
	  <div class="col-auto">
	    <%= form.button "IDI Level 1 Match", type: "submit", name: "identity_matching[idi_level]", value: "idi_patient_l1", class: "btn btn-danger",
						data: { 'bs-toggle' => 'tooltip', 'bs-html' => 'true', 'bs-title' => 'Submit valuable information with a promised minimum <b>weighted value score of 20</b>' }
		%>
	  </div>
	</div>

  </div>
<% end %>

app/views/identity_matchings/_identity_matching.html.erb
<div id="<%= dom_id identity_matching %>" class="card shadow" style="width:24rem;">

  <div class="card-body">
	<h5 class="card-title"><%= identity_matching.full_name %></h5>
	<h6 class="card-subtitle text-muted mb-2">
	  Match attempted <%= identity_matching.updated_at.strftime('%r %x') %>
	</h6>
  </div>

  <ul class="list-group list-group-flush">
    <li class="list-group-item">
      <strong>Date of birth:</strong>
      <%= identity_matching.date_of_birth %>
    </li>

    <li class="list-group-item">
      <strong>Gender:</strong>
      <%= identity_matching.gender&.downcase %>
    </li>

    <li class="list-group-item">
      <strong>Address:</strong>
      <%= identity_matching.address %>
    </li>

    <li class="list-group-item">
      <strong>Email:</strong>
      <%= identity_matching.email %>
    </li>

    <li class="list-group-item">
      <strong>Mobile:</strong>
      <%= identity_matching.mobile %>
    </li>

    <li class="list-group-item">
      <strong>Driver's License:</strong>
      <%= identity_matching.drivers_license %>
    </li>

    <li class="list-group-item">
      <strong>NIPI:</strong>
      <%= identity_matching.national_insurance_payor_identifier %>
    </li>

    <li class="list-group-item">
      <strong>Passport:</strong>
      <%= identity_matching.passport_number %>
    </li>

    <li class="list-group-item">
      <strong>State ID:</strong>
      <%= identity_matching.state_id_number %>
    </li>

    <li class="list-group-item">
      <strong>Level:</strong>
      <%= identity_matching.idi_level&.titleize %>
	  <span class="badge bg-success">Weight = <%= identity_matching.weight %></span>
    </li>
  </ul>

  <div class="card-body">
    <% if identity_matching.response_status %>
      <p>
        <strong>Response status:</strong>
        <%= identity_matching.response_status %>
      </p>
    <% else %>
      <p><strong>Not server response.</strong></p>
    <% end %>

	<%= yield %>
  </div>

</div>

app/views/identity_matchings/edit.html.erb
<h1 class="my-2">Editing Identity</h1>

<%= render "form", identity_matching: @identity_matching %>

<br>

<div>
  <%= link_to "Back", :back %> |
  <%= link_to "See previous identity matches", identity_matchings_path %>
</div>

app/views/identity_matchings/example.html.erb
<h2>Request</h2>
<code>
  <%= @payload %>
</code>

<h2>Response</h2>
<code>
  <%= @response.body %>
</code>

app/views/identity_matchings/index.html.erb
<h1 class="w-100 text-center">Patient Identity Matches</h1>

<div class="row justify-content-between my-3">
  <div class="col-md-4 col-6 text-center">
	<%= link_to "Change Server", root_path, class: "btn btn-secondary" %>
  </div>
  <div class="col-md-4 col-6 text-center">
	<%= link_to "New identity matching request", new_identity_matching_path, class: "btn btn-primary" %>
  </div>
</div>


<div class="row row-cols-md-3 g-2 align-items-around" id="identity_matchings">
  <% @identity_matchings.each do |identity_matching| %>
	<div class="col">
      <%= render identity_matching do %>
        <div class="text-end">
          <%= link_to "Show More", identity_matching %>
        </div>
      <% end %>
	</div>
  <% end %>
</div>

app/views/identity_matchings/new.html.erb
<h1 class="my-2">New Identity</h1>

<p class="lead">
  Will execute <code><%= @patient_server.endpoint %></code>
  <%= link_to "Change Server", root_url, class: "btn btn-sm btn-secondary ms-3" %>
</p>

<%= render "form", identity_matching: @identity_matching %>

<br>

<div>
  <%= link_to "See previous identity matches", identity_matchings_path %>
</div>

app/views/identity_matchings/show.html.erb
<div class="row mt-2 justify-content-between">
  <div class="col">
    <%= link_to "New Match Request", new_identity_matching_path %> |
    <%= link_to "All Identity Matches", identity_matchings_path %>
  </div>
  <div class="col text-end">
    <%= link_to "Delete", "/identity_matchings/#{@identity_matching.id}", data: {turbo_method: :delete}, class: "btn btn-sm btn-dark d-inline" %>
  </div>
</div>

<hr />

<div class="row my-2 justify-content-center">
  <%= render @identity_matching do end %>
</div>

<h3>FHIR Request</h3>
<code class="fhir" style="min-width:100vw;"><%= @identity_matching.request_json %></code>
<hr />

<h3>FHIR Response</h3>
<% if @identity_matching.response_json %>
  <code class="fhir" style="min-width:100vw;"><%= @identity_matching.response_json %></code>
<% elsif @identity_matching.errors.any? %>
  <%= render "errors", identity_matching: @identity_matching %>
<% else %>
  <h6>No valid response obtained from server</h6>
<% end %>