config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get 'welcome/index'
  get 'welcome/terms'
  get 'welcome/privacy'
  get 'welcome/ifconfig'
  get 'index', {controller: :welcome_controller, action: :index}

  get 'patient_server', {controller: :patient_server, action: :show}
  post 'patient_servers', {controller: :patient_server, action: :create}

  get 'identity_matchings/example'
  resources :identity_matchings, except: [:edit, :update]

  get 'oauth2/start'
  get 'oauth2/restart'
  get 'oauth2/redirect'
  #post 'oauth2/register'

  get 'udap/start'
  get 'udap/register'
  get 'udap/redirect'

  resources :authorities

end

app/models/authority.rb
#require_relative '../serializers/pem_serializer.rb'

class Authority < ApplicationRecord

  has_one :certificate # End-entity Certificate object
  serialize :private_key, PEM # OpenSSL::PKey::RSA object

  encrypts :private_key # Rails 7 built-in AES-GCM 128 bit non-deterministic encryption

  validates :name, presence: true, length: {maximum: 255}


  # First try to get public key from OpenSSL::PKey::RSA object
  # Then fallback to OpenSSL::X509::Certificate object
  def public_key
    pkey = self.private_key
    if pkey.public?
        return pkey.public_key
    end

    cert = self.certificate
    return cert.public_key
  end

  # returns trust chain array of OpenSSL::X509::Certificate objects
  def x509_chain
    self.certificate.chain.map(&:x509)
  end

end

app/controllers/authorities_controller.rb
class AuthoritiesController < ApplicationController
  before_action :set_authority, only: %i[ show edit update destroy ]

  # GET /authorities or /authorities.json
  def index
    @authorities = Authority.all
  end

  # GET /authorities/1 or /authorities/1.json
  def show
    render plain: @authority.certificate&.x509&.to_pem # renders certificate PEM or null
  end

  # GET /authorities/new
  def new
    @authority = Authority.new
  end

  # GET /authorities/1/edit
  def edit
  end

  # POST /authorities or /authorities.json
  def create
    @authority = Authority.new(authority_params.slice(:name))
    begin
        ap = authority_params
        der = ap[:pkcs12].read

        pkcs12 = OpenSSL::PKCS12.new( der, ap[:password] )
        @authority.private_key = pkcs12.key
        chain = Certificate.create_chain(*pkcs12.ca_certs)
        @authority.build_certificate({x509: pkcs12.certificate, issuer: chain.first})

        # TODO: certificate chain validation - really server's responsability, but doing client-side is user friendly
    rescue Exception => e
        puts "DEBUG A"

        redirect_to(new_authority_url, {alert: "Error decoding PKCS#12 file: #{e}"}) and return
    end

    puts "DEBUG 6"
    respond_to do |format|
      if @authority.save
        puts "DEBUG 7"
        format.html { redirect_to(udap_start_url, {notice: "Authority #{@authority.name} added successfully."}) }
        format.json { render :show, status: :created, location: @authority }
      else
        puts "DEBUG B"
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @authority.errors, status: :unprocessable_entity }
      end
    end

    puts "------------- end create -------------------"
  end

  # PATCH/PUT /authorities/1 or /authorities/1.json
  def update
    respond_to do |format|
      if @authority.update(authority_params)
        format.html { redirect_to authority_url(@authority), notice: "Authority was successfully updated." }
        format.json { render :show, status: :ok, location: @authority }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @authority.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authorities/1 or /authorities/1.json
  def destroy
    @authority.destroy

    respond_to do |format|
      format.html { redirect_to authorities_url, notice: "Authority was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_authority
      @authority = Authority.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def authority_params
      params.require(:authority).permit(:name, :pkcs12, :password)
    end
end

app/helpers/authorities_helper.rb
module AuthoritiesHelper
end

app/views/authorities/_authority.html.erb
<div id="<%= dom_id authority %>">
  <h2>Trusted Certificate Authority</h2>
    <%= authority.name %>
  </h2>

  <p>
    <strong>Certificate:</strong>
    <%= link_to "View Certificate PEM", authority %>
  </p>

  <p>
    <strong>Private key:</strong>
    REDACTED
  </p>

  <p>
    <strong>Created at:</strong>
    <%= authority.created_at.strftime '%r %x' %>
  </p>

</div>

app/views/authorities/_form.html.erb
<%= form_with(model: authority) do |form| %>
  <% if authority.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(authority.errors.count, "error") %> prohibited this authority from being saved:</h2>

      <ul>
        <% authority.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div>
    <%= form.label "Upload *.p12 file, which bundles RSA private key, public key, and certificate chain of trust", style: "display: block" %>
    <%= form.file_field :pkcs12, class: "form-control", placeholder: "*.p12 file" %>
  </div>

  <div>
    <%= form.label "Passphrase if your *.p12 file is passphrase protected", style: "display: block" %>
    <%= form.password_field :password, class: "form-control", placeholder: "Passphrase" %>
  </div>

  <div>
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/authorities/edit.html.erb
<h1>Editing authority</h1>

<%= render "form", authority: @authority %>

<br>

<div>
  <%= link_to "Back", :back %>
</div>

app/views/authorities/index.html.erb
<h1>Trusted Certificate Authorities</h1>

<p>A proper identity matching or UDAP client must obtain a private key and certificate from an authority. Then UDAP resource servers and patient matching servers
will allow the clients access if the server providers trust the certificate authority.</p>

<table id="authorities" class="table">
  <tr>
    <th>Name</th>
    <th>Created</th>
    <th>Certificate</th>
    <th colspan="2">Actions</th>
  </tr>
  <% @authorities.each do |authority| %>
  <tr>
    <td><%= authority.name %></td>
    <td><%= authority.created_at.strftime '%r %x' %></td>
    <td><%= link_to "Download PEM", authority, download: authority.name.parameterize + ".pem" %></td>
    <td><%= link_to "Edit", edit_authority_path(authority), class: "text-success" %></td>
    <td><%= button_to "Delete", authority, method: :delete, class: "btn btn-sm btn-danger" %></td>
  </tr>
  <% end %>
</table>

<%= link_to "New authority", new_authority_path, class: "btn btn-primary" %>

app/views/authorities/new.html.erb
<h1>New authority</h1>

<p class="lead">
Adding a new authority includes their private key and <a href="https://datatracker.ietf.org/doc/html/rfc5280">X509 Certificate Chain</a>,&nbsp;
which allows the client to assert signed software statements that servers can trust based on the certificates.
</p>

<%= render "form", authority: @authority %>

<br>

<div>
  <%= link_to "Back", :back %> |
  <%= link_to "View all authorities", authorities_url %>
</div>

app/views/authorities/show.html.erb
<%# replaced by plain certificate PEM %>