config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get 'welcome/index'
  get 'welcome/terms'
  get 'welcome/privacy'
  get 'welcome/ifconfig'
  get 'index', {controller: :welcome_controller, action: :index}

  get 'patient_server', {controller: :patient_server, action: :show}
  post 'patient_servers', {controller: :patient_server, action: :create}

  get 'identity_matchings/example'
  resources :identity_matchings, except: [:edit, :update]

  get 'oauth2/start'
  get 'oauth2/restart'
  get 'oauth2/redirect'
  #post 'oauth2/register'

  get 'udap/start'
  get 'udap/register'
  get 'udap/redirect'

  resources :authorities

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Identity Matching Client</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="robots" content="noindex,nofollow">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

	<script>
	</script>
  </head>

  <body>
	<div class="position-relative" style="z-index:1;">
	  <!-- flash notice message -->
	  <% if notice %>
		<div class="alert alert-success alert-dismissible fade show mb-0" role="alert">
		  <strong>Notice:</strong> <%= notice %>
		  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
		</div>
	  <% end %>

	  <!-- flash alert message -->
	  <% if alert %>
		<div class="alert alert-danger alert-dismissible fade show" role="alert">
		  <strong>Alert:</strong> <%= alert %>
		  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
		</div>
	  <% end %>
	</div>

    <main class="container-fluid">
      <%= yield %>
	</main>

    <footer class="container-fluid mt-3 text-center">
	  <hr />
	  &copy; MITRE 2022 |
      FHIR&reg; is a registered trademark of HL7&reg; |
      <%= link_to "Index", root_url %> |
      <%= link_to "Terms", welcome_terms_url %> |
      <%= link_to "Privacy", welcome_privacy_url %> |
      <%= link_to "Cookies", welcome_privacy_url + '#cookies' %>
    </footer>
  </body>
</html>